In [2]:
import numpy as np
import rnn_utils


In [3]:
def rnn_cell_forward(xt, a_prev, parameters):
    """
    根据图2实现RNN单元的单步前向传播
    
    参数：
        xt -- 时间步“t”输入的数据，维度为（n_x, m）
        a_prev -- 时间步“t - 1”的隐藏隐藏状态，维度为（n_a, m）
        parameters -- 字典，包含了以下内容:
                        Wax -- 矩阵，输入乘以权重，维度为（n_a, n_x）
                        Waa -- 矩阵，隐藏状态乘以权重，维度为（n_a, n_a）
                        Wya -- 矩阵，隐藏状态与输出相关的权重矩阵，维度为（n_y, n_a）
                        ba  -- 偏置，维度为（n_a, 1）
                        by  -- 偏置，隐藏状态与输出相关的偏置，维度为（n_y, 1）
    
    返回：
        a_next -- 下一个隐藏状态，维度为（n_a， m）
        yt_pred -- 在时间步“t”的预测，维度为（n_y， m）
        cache -- 反向传播需要的元组，包含了(a_next, a_prev, xt, parameters)
    """
    
    # 从“parameters”获取参数
    Wax = parameters["Wax"]
    Waa = parameters["Waa"]
    Wya = parameters["Wya"]
    ba = parameters["ba"]
    by = parameters["by"]
    
    # 使用上面的公式计算下一个激活值
    a_next = np.tanh(np.dot(Waa, a_prev) + np.dot(Wax, xt) + ba)
    
    # 使用上面的公式计算当前单元的输出
    yt_pred = rnn_utils.softmax(np.dot(Wya, a_next) + by)
    
    # 保存反向传播需要的值
    cache = (a_next, a_prev, xt, parameters)
    
    return a_next, yt_pred, cache
    


In [4]:
np.random.seed(1)
xt = np.random.randn(3,10)
a_prev = np.random.randn(5,10)
Waa = np.random.randn(5,5)
Wax = np.random.randn(5,3)
Wya = np.random.randn(2,5)
ba = np.random.randn(5,1)
by = np.random.randn(2,1)
parameters = {"Waa": Waa, "Wax": Wax, "Wya": Wya, "ba": ba, "by": by}

a_next, yt_pred, cache = rnn_cell_forward(xt, a_prev, parameters)
print("a_next[4] = ", a_next[4])
print("a_next.shape = ", a_next.shape)
print("yt_pred[1] =", yt_pred[1])
print("yt_pred.shape = ", yt_pred.shape)


a_next[4] =  [ 0.59584544  0.18141802  0.61311866  0.99808218  0.85016201  0.99980978
 -0.18887155  0.99815551  0.6531151   0.82872037]
a_next.shape =  (5, 10)
yt_pred[1] = [0.9888161  0.01682021 0.21140899 0.36817467 0.98988387 0.88945212
 0.36920224 0.9966312  0.9982559  0.17746526]
yt_pred.shape =  (2, 10)


In [7]:
x = np.random.randn(3,10,4)
x

array([[[-0.43750898,  0.09542509,  0.92145007,  0.0607502 ],
        [ 0.21112476,  0.01652757,  0.17718772, -1.11647002],
        [ 0.0809271 , -0.18657899, -0.05682448,  0.49233656],
        [-0.68067814, -0.08450803, -0.29736188,  0.417302  ],
        [ 0.78477065, -0.95542526,  0.58591043,  2.06578332],
        [-1.47115693, -0.8301719 , -0.8805776 , -0.27909772],
        [ 1.62284909,  0.01335268, -0.6946936 ,  0.6218035 ],
        [-0.59980453,  1.12341216,  0.30526704,  1.3887794 ],
        [-0.66134424,  3.03085711,  0.82458463,  0.65458015],
        [-0.05118845, -0.72559712, -0.86776868, -0.13597733]],

       [[-0.79726979,  0.28267571, -0.82609743,  0.6210827 ],
        [ 0.9561217 , -0.70584051,  1.19268607, -0.23794194],
        [ 1.15528789,  0.43816635,  1.12232832, -0.9970198 ],
        [-0.10679399,  1.45142926, -0.61803685, -2.03720123],
        [-1.94258918, -2.50644065, -2.11416392, -0.41163916],
        [ 1.27852808, -0.44222928,  0.32352735, -0.10999149],
      

In [8]:
x[:,:,0]

array([[-0.43750898,  0.21112476,  0.0809271 , -0.68067814,  0.78477065,
        -1.47115693,  1.62284909, -0.59980453, -0.66134424, -0.05118845],
       [-0.79726979,  0.9561217 ,  1.15528789, -0.10679399, -1.94258918,
         1.27852808,  0.00854895, -1.17598267,  0.80539342, -0.19022103],
       [ 0.93916874,  0.7278135 ,  0.32427424, -0.41302931, -0.785534  ,
         0.0353601 , -0.18417633, -0.53302033,  0.47761018,  0.92061512]])

In [6]:
contact = np.random.rand(8, 10)

In [7]:
contact

array([[0.902648  , 0.7739328 , 0.92854251, 0.09441789, 0.55165361,
        0.89575988, 0.20701984, 0.26430163, 0.52202615, 0.33922358],
       [0.33907756, 0.98433419, 0.48398865, 0.81256897, 0.25317378,
        0.56629574, 0.04363275, 0.28808177, 0.15337724, 0.84181469],
       [0.13693985, 0.53546359, 0.87849981, 0.57769105, 0.3329086 ,
        0.94277815, 0.10396066, 0.34067865, 0.26628655, 0.6310612 ],
       [0.40553365, 0.80818372, 0.90303529, 0.40969253, 0.13163771,
        0.30108534, 0.77489775, 0.13376941, 0.74069176, 0.45757217],
       [0.79209952, 0.96028107, 0.0728947 , 0.79176233, 0.5297754 ,
        0.22019213, 0.32229335, 0.68601746, 0.35497845, 0.94451752],
       [0.44549345, 0.22000827, 0.44156112, 0.3266456 , 0.87191959,
        0.73911351, 0.49197275, 0.16091334, 0.07408526, 0.83903373],
       [0.17723672, 0.0210403 , 0.28643058, 0.21896609, 0.61623636,
        0.12137369, 0.36995228, 0.14987793, 0.5885196 , 0.56659916],
       [0.15639544, 0.18877098, 0.1226860

In [8]:
contact.shape

(8, 10)

In [13]:
contact[0:1,0:1]

array([[0.902648]])

In [14]:
da = np.random.randn(5, 10, 4)

In [17]:
da[:,:,3]

array([[ 1.03949103, -0.76841832, -0.39170437, -0.14532725,  0.80076421,
        -0.31091565,  0.03089603, -0.50456153, -0.06050979, -0.74900611],
       [-0.4569927 ,  0.03119835, -0.28294778, -1.54034125,  1.17597294,
         0.69315835,  0.81564948,  1.29459117, -0.3645401 ,  0.96094206],
       [ 0.26073979, -0.63026602,  1.21122713, -0.0899542 , -0.37370432,
         0.37445193,  0.36300819,  0.3954043 ,  0.1626245 , -0.05174911],
       [ 2.15259447,  1.28123191, -0.16192001, -0.34470335, -0.10144382,
        -1.25721021, -0.32647185,  0.06428458, -1.43259701,  0.71765104],
       [-0.10615335,  0.30154612,  0.77281812,  1.24453807, -1.39465147,
         1.04604539,  1.54169785,  0.18534843,  0.94547706, -1.81645024]])

In [18]:
da_prevt = np.zeros([5, 10])

In [19]:
da[:,:,3] + da_prevt

array([[ 1.03949103, -0.76841832, -0.39170437, -0.14532725,  0.80076421,
        -0.31091565,  0.03089603, -0.50456153, -0.06050979, -0.74900611],
       [-0.4569927 ,  0.03119835, -0.28294778, -1.54034125,  1.17597294,
         0.69315835,  0.81564948,  1.29459117, -0.3645401 ,  0.96094206],
       [ 0.26073979, -0.63026602,  1.21122713, -0.0899542 , -0.37370432,
         0.37445193,  0.36300819,  0.3954043 ,  0.1626245 , -0.05174911],
       [ 2.15259447,  1.28123191, -0.16192001, -0.34470335, -0.10144382,
        -1.25721021, -0.32647185,  0.06428458, -1.43259701,  0.71765104],
       [-0.10615335,  0.30154612,  0.77281812,  1.24453807, -1.39465147,
         1.04604539,  1.54169785,  0.18534843,  0.94547706, -1.81645024]])